# Generated by Django 5.0 on 2023-12-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='banker',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
