# Generated by Django 5.0 on 2023-12-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0013_alter_acountnumbers_options'),
        ('transactions', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transfer',
        ),
    ]
