# Generated by Django 5.0 on 2023-12-26 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0013_alter_acountnumbers_options'),
        ('transactions', '0007_rename_transaction_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='banker',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_account', models.TextField(max_length=20, verbose_name='Receiver Account Number')),
                ('type', models.CharField(choices=[('Transfer', 'Transfer'), ('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], default='Transfer', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge', models.DecimalField(decimal_places=2, default=0.8, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff who proccessed Withdrawal or deposit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='banker', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing', to='bank_profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankChargeRevenue',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_revenue', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
