# Generated by Django 5.0 on 2023-12-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_delete_bankchargerevenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='comment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='comment',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
