# Generated by Django 5.0 on 2023-12-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountNumberCheker',
        ),
    ]
