# Generated by Django 5.0 on 2023-12-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_allacountnumbers_account_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllAcountNumbers',
        ),
    ]
