# Generated by Django 5.0 on 2023-12-15 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transfer_pin',
            field=models.CharField(default=123456, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
