# Generated by Django 5.0 on 2023-12-15 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_transfer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transfer_pin',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
