# Generated by Django 5.0 on 2023-12-15 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_no',
            field=models.CharField(default='833283039', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transfer_pin',
            field=models.CharField(default='123456', validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
