# Generated by Django 5.0 on 2023-12-16 09:39

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_account_no_alter_profile_transfer_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Eg: +234758849930', max_length=30, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transfer_pin',
            field=models.CharField(default=123456, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
