# Generated by Django 5.0 on 2023-12-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_otpforuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
