# Generated by Django 5.0 on 2023-12-20 11:39

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Account balance')),
                ('transfer_pin', models.CharField(default=123456, validators=[django.core.validators.MinLengthValidator(4)])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Eg: +234758849930', max_length=30, null=True, region=None, verbose_name='Phone Number')),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='profile_images', verbose_name='Profile Photo')),
                ('verification_method', models.CharField(choices=[('NIN', 'NIN'), ('DRIVING_LICENCE', 'DRIVING_LICENCE'), ('PASSPORT', 'PASSPORT')], default='NIN', max_length=50)),
                ('Verification_id', models.ImageField(blank=True, null=True, upload_to='Verification_images', verbose_name='Verification_id')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Your Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
