# Generated by Django 5.0 on 2023-12-20 12:52

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0003_allacountnumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allacountnumbers',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Verification_id',
            field=models.ImageField(null=True, upload_to='Verification_images', verbose_name='Verification_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(max_length=255, null=True, verbose_name='Your Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Eg: +234758849930', max_length=30, null=True, region='NG', verbose_name='Phone Number'),
        ),
    ]
