# Generated by Django 5.0 on 2023-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0004_remove_allacountnumbers_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_method',
            field=models.TextField(choices=[('NIN', 'NIN'), ('DRIVING_LICENCE', 'DRIVING_LICENCE'), ('PASSPORT', 'PASSPORT')], default='NIN', help_text='NIN, DRIVING_LICENCE, PASSPORT', max_length=50),
        ),
    ]
