# Generated by Django 5.0 on 2023-12-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0006_profile_is_updated_alter_allacountnumbers_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allacountnumbers',
            name='account_no',
            field=models.TextField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
