# Generated by Django 5.0 on 2023-12-22 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0007_alter_allacountnumbers_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transfer_pin',
            field=models.TextField(default='1234', validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
