# Generated by Django 5.0 on 2023-12-22 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0008_alter_profile_transfer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transfer_pin',
            field=models.CharField(default='1234', max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
