# Generated by Django 5.0 on 2023-12-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0012_rename_allacountnumbers_acountnumbers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acountnumbers',
            options={'verbose_name_plural': 'AccountNumbers'},
        ),
    ]
