# Generated by Django 5.0 on 2023-12-27 10:18

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0013_alter_acountnumbers_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Eg: +234758849930', max_length=30, region='NG', verbose_name='Phone Number')),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='Next_of_kin', verbose_name='Profile Photo')),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='Country')),
                ('city', models.TextField(max_length=100, verbose_name='City')),
                ('address', models.TextField(max_length=255, verbose_name='Your Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.TextField(choices=[('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Seperated', 'Seperated'), ('Single', 'Single')], default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transfer_pin',
            field=models.TextField(default='1234', max_length=255, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefactor', to='bank_profiles.nextofkin'),
        ),
    ]
