# Generated by Django 5.0 on 2023-12-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_profiles', '0014_nextofkin_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Account balance'),
        ),
    ]
